name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/chekout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/InF1nitySun/top-api-demo/top-api-demo
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"