name: Publish Docker

on:
  push:
    branches: [master]
permissions:
  id-token: write
  contents: read # default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          token: ${{ secrets.MY_NEW_TOKEN }}
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/InF1nitySun/top-api-demo/top-api-demo
          tags: "develop"